steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/perceivo_backend_api:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'perceivo-backend-service', '--image', 'gcr.io/$PROJECT_ID/perceivo_backend_api:$COMMIT_SHA', '--platform', 'managed', '--region', 'asia-southeast2', '--allow-unauthenticated', '--memory', '1Gi', '--cpu', '1']
options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: gs://cloud-build-logs-0
images:
  - 'gcr.io/$PROJECT_ID/perceivo_backend_api:$COMMIT_SHA'
